name: check_homework
on: [push]
jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: dependencies
      run: |
        sudo apt install flake8
    - name: Flake8
      run: cd django_sirius && flake8
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: python3 manage.py test
